preview-src/ui-model.yml, src/js/01-nav.js, src/stylesheets/header.scss
- Use local storage to persist theme value
- Init theme at load by retrieving value in local storage
- Remove transition on toggle to avoid unwanted movement when a page is loaded
=> feat(theme): persist theme value

src/partials/header-content.hbs, src/stylesheets/header.scss
Change search input placeholder color on mouse hover and on focuse.
=> feat (header): Improve search placeholder color on hover and on focus

preview-src/misc.adoc, src/stylesheets/doc.scss
- Remove special css rule for list -> no more issues
=> Fix admonitions is lists

README.adoc
- Add some details on how to use the UI bundle in the main docsite repo
- Add some details to simply change colors in the UI (probably one of the main future use case)
- Add some links to help future maintainers to perform structural changes
=> doc(readme): create readme content

preview-src/ui-model.yml, src/partials/header-content.hbs, src/stylesheets/globals/vars.scss, src/stylesheets/header.scss
covers https://github.com/bonitasoft/bonitasoft.github.io/issues/111
=> feat: let use a dedicated navbar for non production environment

package-lock.json, package.json, src/js/06-docsearch.js, src/partials/footer-scripts.hbs
Better than creating http request manually
=> Use algolia js library to send click events

preview-src/misc.adoc, src/stylesheets/base.scss, src/stylesheets/breadcrumbs.scss, src/stylesheets/doc.scss, src/stylesheets/globals/vars.scss, src/stylesheets/nav.scss, src/stylesheets/toc.scss
- Update bold policy: remove the 'bolder var', only use one bold var -> to much, leads do unwanted behavior on the TOC
- Update Dark highlight color -> Titles and current page are more visible, improve consistency with light theme
=> Misc UI update

src/partials/article.hbs, src/partials/header-content.hbs, src/stylesheets/doc.scss
* display search bar when page-hide-search-bar is set to true
* Adding blue panel when page-next-release is set to true
=> feat(nextVersion): Hide search bar and display blue panel

.github/actions/build-setup/action.yml, .github/workflows/build-artifacts.yml, .github/workflows/commit-message-check-format.yml, .github/workflows/publish-pr-preview.yml, README.adoc, package-lock.json
covers https://github.com/bonitasoft/bonita-documentation-site/issues/268
covers https://github.com/bonitasoft/bonita-documentation-site/issues/269
=> chore: bump to node 16 and simplify github workflows

package-lock.json, src/js/header-01-theme.js, src/stylesheets/breadcrumbs.scss, src/stylesheets/globals/vars.scss, src/stylesheets/nav.scss, src/stylesheets/toc.scss
- We do not increase the font weight on hover (in the nav, the toc...) -> no more 'flash' effect
- Add a dedicated color for hover, so the contrats is better on light theme
=> theme: Improve hover behavior

package-lock.json, preview-src/misc.adoc, src/js/header-01-theme.js, src/stylesheets/doc.scss, src/stylesheets/globals/vars.scss
- Update bg and color
- Apply the style in call out
- Update node module cached-path-relative
=> feat(code blocks): improve monoline code block visibility

src/js/header-01-theme.js, src/stylesheets/globals/vars.scss, src/stylesheets/header.scss
This new way to manage theme will allow us to natively benefit from the dark theme provided by docsearch
=> feat: Update the way theme is applied -> huge perf improvment

src/partials/article.hbs, src/partials/toolbar.hbs, src/stylesheets/doc.scss, src/stylesheets/globals/vars.scss, src/stylesheets/toolbar.scss
- Custom messages do not scroll anymore, and are always visible.
Covers https://github.com/bonitasoft/bonita-documentation-site/issues/274
=> feat(custom_messages): Custom messages are now always visible

src/partials/toolbar.hbs, src/stylesheets/toolbar.scss
- "custom message" is now better presented on 2 lines
- "out of support" message has now links more visible (underlined)
=> feat(custom_message): Improve custom message

gulp.d/tasks/build-preview-pages.js, package-lock.json, package.json, preview-src/misc.adoc
* allow using collapsible blocks in the preview source content
Cover https://github.com/bonitasoft/bonita-documentation-site/issues/325
=> chore(ascidoc2): Use ascidoc2 in theme preview

src/stylesheets/toolbar.scss
When scrolling up, the toolbar is moving up little a bit.
=> fix(toolbar): Fix a glitch in toolbar when scrolling

preview-src/admonitions.adoc, preview-src/code.adoc, preview-src/media.adoc
* If we follow our example (copy paste), we don't reproduce the right behavior.
=> fix(example): remove usage of ++++ in example

src/partials/footer-scripts.hbs
* remove script section to section added only when site is on production
=> theme(asciinema): Use js library not only on production

src/stylesheets/components/cards.scss
* Actual displaying is very aggressive, I would try to update it
=> theme(card): improve card hover styling

src/partials/pagination.hbs, src/stylesheets/globals/vars.scss, src/stylesheets/pagination.scss
First proposal, fell free to comments 
Cover https://github.com/bonitasoft/bonita-documentation-site/issues/362
=> feat: improve navigation display

.github/workflows/commit-message-check-format.yml, .github/workflows/create-release.yml, .github/workflows/create-tag.yml, .github/workflows/publish-online-example.yml, .github/workflows/publish-pr-preview.yml
See also https://github.com/bonitasoft/bonita-documentation-site/pull/447
=> ci: run all GitHub workflows on Ubuntu 22.04

preview-src/troubleshooting.adoc
* update example with code block
* Add Troubleshooting title example
=> docs: improve live example troubleshooting

src/partials/nav-menu.hbs, src/stylesheets/globals/vars.scss, src/stylesheets/nav.scss
=> feat: Improve table of contents

.github/workflows/publish-online-example.yml, .github/workflows/publish-pr-preview.yml, gulp.d/tasks/build-preview-pages.js
* Allow to declare extensions
* Use Asciidoctor/core
=> chore: Update build-preview from antora-ui

src/partials/header-content.hbs
Fixes https://github.com/bonitasoft/bonita-documentation-theme/issues/218
=> fix(nav): filter hidden component from mobile nav

.github/dependabot.yml
Also change the day when dependabot tries to update GH Actions
=> chore(dependabot): update npm production dependencies

preview-src/ui-model.yml, src/partials/header-content.hbs, src/stylesheets/header.scss
* Adding a <a> tag on title
* The href use in the <a> tag is taken from the new "prLink" antora keys
Covers https://github.com/bonitasoft/bonita-documentation-site/issues/584
=> feat: Allow to navigate from the live preview to the PR
