.github/workflows/workflow-build.yml, README.adoc
Changes
- Upload the preview to have a quick overview of what changed in the Antora UI bundle
- Have more consistent builds (same as we do in https://github.com/bonitasoft/bonitasoft.github.io)
- enforce the ubuntu version of the runner
- run npm ci instead of npm install to ensure we use lock versions for dependencies (see https://docs.npmjs.com/cli/v6/commands/npm-ci)
- enforce the node version to 12.x to avoid depending on the default installed on the runner and that can change at any time
- uploaded artifacts have an unique name at each build for a better identification
Warning fixed by this PR
=> chore(ci): also upload the preview

preview-src/ui-model.yml, src/helpers/versionSorter.js, src/partials/nav-explore.hbs, src/partials/page-versions.hbs
- A special version "other" has been added for old Bonita versions -> it has the lowest priority
- Version 'latest' has always the highest priority
- Other versions are sorted using semver
=> Custom sorter for versions

README.adoc, preview-src/ui-model.yml, src/partials/header-content.hbs, src/partials/toolbar.hbs
**Will be used by https://github.com/bonitasoft/bonitasoft.github.io/pull/190**
Hide 'edit page links'
We don't want to display such links in documentation archives we want to make
available for download only.
In this case, the documentation content source code is not available locally
so keeping the links is just misleading.
Hide 'components list' in the navbar
For single component version archive, this is not need as we have a single
component. In addition, the link produced for component in this list doesn't
work for local file browsing.
=> feat: add settings to improve documentation archives generation

README.adoc
This is now 'bonita-documentation-site'.
covers https://github.com/bonitasoft/bonita-documentation-site/issues/167
=> doc: update after the rename of the 'bonitasoft.github.io' repository

preview-src/misc.adoc, src/stylesheets/doc.scss
Custom size can be used on desktop (and will be tested by the contributor), but we must lock it for mobile view else the iframe will take too much space.
=> lock video size on mobile

src/partials/footer-scripts.hbs
- Display 20 hits instead of 5 to ensure that for a given query users have a good chance to find the page they are looking for.
[WWW-982](https://bonitasoft.atlassian.net/browse/WWW-982)
=> Update number of hits displayed by the search

preview-src/index.adoc, src/stylesheets/components/cards.scss
This pr make the card css more flexible: 
A balise `<div class="sectionbody">` is added by the asciidoctor convertor under the lvl 1 and 2 titles, but not for other levels. 
The presence of this div impacts the cards css, if the balise is missing the css isn't applied. 
So we improved the css to apply it whether the div is present or not.
=> fix(cards): support cards under title lvl 3 and more

.github/workflows/commit-message-check-format.yml
We are only checking the PR title and description so we don't need to checkout (we are not considering the repository code here).
=> chore(wf): no checkout for PR convention checks

src/partials/footer-scripts.hbs, src/partials/head-styles.hbs
This avoids loading useless resources when the search is not available in the
page. It previously generated a JS error because some HTML element was not
present in the page.
Also use specific version of docsearch resources to improve caching and use SRI.
covers https://github.com/bonitasoft/bonita-documentation-site/issues/235
=> chore: only load docsearch resources when search is displayed

src/helpers/isNotApiComponent.js, src/partials/nav.hbs, src/partials/toc.hbs
We don't have component using the 'bonitaAPI' component.name. So, there is no
reason for filtering such component in nav and toc.
This seems to be a remaining part of the POC done in 2020: we were trying to
integrate the Bonita API documentation within the site. We don't have such API
in the site for now.
=> feat: remove the 'isNotApiComponent' handlebars macro

preview-src/misc.adoc, src/stylesheets/doc.scss, src/stylesheets/globals/vars.scss
Use dedicated colors for table separators in admonitions: the default gray leads to some unwanted visual effects when used in admonitions: A tiny gray line with a green background looks a bite pink, with a purple background it looks a bit green, and so on for other admonitions. 
So instead of keeping this, I use dedicated colors for table separator in admonitions. 
Before: 
After:
=> feat(table): Improve colors in admonitions with table content

src/partials/toolbar.hbs, src/stylesheets/globals/vars.scss, src/stylesheets/toolbar.scss
--toolbar-height var is back to its original value, since it was used also by version block
- A new var defines the height of the header message: --header-message-height (still hard-coded with a 2-lines message)
- A width 100% was missing for the next-release-block
=> fix(custom_message):  Fix side effect of "custom message always visible"

preview-src/msg-block-custom-message.adoc, preview-src/msg-block-next-version.adoc, preview-src/msg-block-out-of-support.adoc, preview-src/ui-model.yml, src/partials/toolbar.hbs, src/stylesheets/toolbar.scss
In a previous change, we made the links in the toolbar message blocks more visible by underlining them. This introduced
a side effect on the links of the breadcrumbs that were also underlined.
This is now fixed and dedicated pages have been created to easily test the rendering of all kinds of messages.
In addition, refactor the CSS classes of the message blocks
- remove duplication
- apply underline to anchor inside the message blocks, not in the other toolbar elements
- introduce a dedicated css class for custom message block for clarity (even if the definition is the same as the one
for next version block)
**Live site showing the introduced issue**
[Without the issue](https://624e56d7e9c25f10b7116a7e--documentation-bonita.netlify.app/bonita/2022.1/identity/profiles-overview) | With the …
=> fix: don't underline link in breadcrumbs

preview-src/admonitions.adoc, preview-src/asciinema.adoc, preview-src/cards.adoc, preview-src/media.adoc, preview-src/troubleshooting.adoc
Explanations were previously in the contributing documentation: see https://github.com/bonitasoft/bonita-documentation-site/pull/346
=> doc: move example from contributing to online example

src/stylesheets/base.scss, src/stylesheets/doc.scss
Videoblock section style is like other block section (image block for example)
before
after
Scroll animation is improved, see this following example 
Before
After
=> theme: minor theme improvement (smooth scroll, video block)

preview-src/bonita/2021.1/index.adoc, preview-src/ui-model.yml
In Antora 3, the model is `page.component.latest`. It was previously `page.component.latestVersion`
The hbs templates have been updated but the source preview model still refers to the old property.
So the links to the latest version in preview pages weren't resolved.
The hbs template were fixed with #80
=> chore: update the latest version property in ui-model.yml

.github/workflows/create-release.yml, .github/workflows/create-tag.yml, README.adoc
Add new workflows to manage the release:
- create_tag action bump the version and push the tag (format: v1.0.0)
- create_release action:
- Generate the theme bundle 
- Update the bundle name to include the version
- Send a Repository Dispatch event to the doc-site repo with the release version, the bundle file name and its url
Update the documentation of the release process
Covers (theme part) [Find a way to not be forced to store the Antora UI bundle in the repository](https://github.com/bonitasoft/bonita-documentation-site/issues/47)
=> chore: automate the ui bundle release

.github/release.yml
PRs will be separated in different sections:
- 'bug' label -> 'Bug Fixes'
- 'enhancement' label -> 'New Features'
- any other label (but the excluded ones below) -> 'Other Changes'
PRs with the following labels will be excluded from the generated release notes:
- dependencies
- github_actions
- ignore-for-release-notes (used when there is no existing tag)
Note that we may add other labels to exclude later, if needed.
See the release test: https://github.com/jeromecambon/bonita-documentation-theme/releases/tag/v0.27.0
Covers [Configure the theme repository GitHub auto-generated release notes](https://github.com/bonitasoft/bonita-documentation-site/issues/375)
=> chore(release-notes): Configure generated release notes by section

preview-src/msg-block-out-of-support.adoc, src/helpers/isSearchBarDisplayed.js, src/partials/article-404.hbs, src/partials/article.hbs, src/partials/footer-scripts.hbs, src/partials/head-styles.hbs, src/partials/header-content.hbs, src/partials/main.hbs
Previously, the 404-page display the search bar that did a search on all versions of all components
which was not convenient.
Introduce a Handlebar helper function to manage all options that hide the search bar. This removes
duplication logic.
Also include refactoring from Antora Default UI "move article tag for 404 to separate partial"
(cherry picked from commit 0706e75dd621f4e67108d2ca887be2d0a97c67fe)
closes https://github.com/bonitasoft/bonita-documentation-site/issues/271
All preview pages display the search bar except
- the 404 page
- the out of support page as it is configured to hide it with a dedicated attribute
Locally changing the ui-model.yml to for the preview in "non production": the search bar is hidden in all pages
=> fix: hide search bar in page 404

.github/workflows/publish-pr-preview.yml
Don't create the preview when dependabot builds the PR: the surge token is not available.
On PR close, don't teardown the surge domain when it doesn't exist (this prevents error).
closes https://github.com/bonitasoft/bonita-documentation-site/issues/361
see also https://github.com/bonitasoft/bonita-documentation-site/pull/378
=> chore: better manage surge preview for PR built by dependabot

src/stylesheets/doc.scss
- Applied the chosen css from the issue below
- Tested light and dark themes, on Chrome/Safari/Firefox
Covers [Source code rendering: make the callout more visible](https://github.com/bonitasoft/bonita-documentation-site/issues/244)
=> theme(callout): Make asciidoc callout more visible for source code

package.json
Related to [retrieve highlight.js from npm](https://github.com/bonitasoft/bonita-documentation-theme/issues/126)
=> chore(clean dependency): Remove unused package.json dependency

src/partials/footer-content.hbs, src/partials/page-additional-icons.hbs, src/partials/toolbar.hbs
Use the `{{{uiRootPath}}}` template variable instead of hard coded path. The hard coded path works with the theme preview but not when used to build the site.
Closes #149
This change requires **manual testing**.
Build a part of the site using the new bundle. See https://github.com/bonitasoft/bonita-documentation-site#using-local-ui-bundle
For instance, with something like `./build-preview-dev.bash --local-ui-bundle  --use-test-sources`
=> fix: display the images in footer and "edit this page"

src/stylesheets/toolbar.scss
Display the page icons (edit, history, contribute) whatever the browser window size is.
Previously the page icons were not displayed for window < 1024px.
closes #152
=> feat(page_icons): Always display the page icons

.github/actions/build-setup/action.yml
Remove deprecation warnings:
- run with node16
- use the new way to set states and outputs
=> chore(deps-gha): bump actions/node from v2 to v3

src/stylesheets/nav.scss
The toggle button of the navigation (TOC) is now centered on the item, and a bit moved away from the item. See [screenshots](https://github.com/bonitasoft/bonita-documentation-theme/pull/176#issuecomment-1415501794).
=> fix: TOC toggle position

.gitignore, src/stylesheets/header.scss
Center and enlarge the title when using the "nonProduction" mode which is activated for PR preview and archive.
before | after
---- | ----
This can be tested locally by
- in preview-src/ui-model.yml, set  `nonProduction: true`
- run 'npm run dev' and access to the preview
=> feat: improve the title display for PR preview

gulp.d/tasks/build.js
* In 37df10aa7b685b60c20d0aa7541ee36ab920396c we introduce some lint issue that break the release workflow
=> refactor: Fix format issue

preview-src/ui-model.yml, src/helpers/isSearchBarDisplayed.js
Even when the site is built in non production mode (specific nav bar color), this change lets display the search bar in the pages where the search bar is not hidden. This will let test the search in PR preview in the documentation-site repository.
Relates to https://github.com/bonitasoft/bonita-documentation-site/pull/520
Tests done with https://github.com/bonitasoft/bonita-documentation-site/pull/558
=> feat: let display the search bar in preview

src/partials/footer-scripts.hbs
Pass both the actual version and the version aliases (latest or next) when available.
This ensures a smooth transition when `Antora` will manage the latest and next aliases. `DocSearch` doesn't know the aliases until the site is in production and it has been re-indexed.
During the transition, the search will work for readers (as indexed with the actual version) and also after the content has been re-indexed (using the alias).
In addition, remove the old commented code related to `DocSearch` click events. We will eventually enable it later.
See related PR: https://github.com/bonitasoft/bonita-documentation-site/pull/520
See issue: https://github.com/bonitasoft/bonita-documentation-site/issues/419
With the DocSearch client of the Crawler, when we select 2 versions for the search, here is …
=> feat: pass version aliases to DocSearch

.github/workflows/publish-pr-preview.yml
This lets us test the built theme preview locally whatever the author of the PR is. This is particularly useful for PR from dependabot or from fork (the preview is not published on a surge domain).
=> ci: make the PR preview always available as a GH artifact

gulp.d/tasks/build.js, package-lock.json, package.json
Some fonts were incorrectly filtered.
Font URLs to filter are:
```
~typeface-roboto-mono/files/roboto-mono-latin-400.woff2
~typeface-roboto-mono/files/roboto-mono-latin-400.woff
~typeface-roboto-mono/files/roboto-mono-latin-500.woff2
~typeface-roboto-mono/files/roboto-mono-latin-500.woff
```
=> fix(postcss): fix regex to filter css to exec postcss

preview-src/hide-components-entry.adoc, preview-src/ui-model.yml, src/helpers/isComponentToHide.js, src/partials/header-content.hbs, src/partials/nav-explore.hbs
* Create a new helper to filter components array
* Adding an example page in preview site
closes #214
=> feat: filter components from hide-component attribues

.github/workflows/publish-online-example.yml
We don't need to keep a history of the built site, so we can get rid of the gh-pages branch. In addition, we are sure to now have a fresh deploy. With the branch, some extra files are kept except if they are removed manually.
Removing the branch will also reduce the size of the repository.
After merging this PR, the configuration of the repository must be changed to switch the GitHub Pages configuration from branch to GH Actions
=> ci: deploy to gh-pages with GitHub Actions

README.adoc, preview-src/ui-model.yml, src/partials/toolbar.hbs
Previously, in the "out of support", the link to the "latest" resource was always targeting the home page of the latest version of the component.
Now, the link targets the latest version of the current page when it exists. The template use the "relativize" helper to make the url work with local file browsing
Also update the `model-ui.yml` used for the preview to demonstrate the change.
Closes #203
Tested with preview source
- see https://bonitasoft-bonita-documentation-theme-build_preview-pr-230.surge.sh/msg-block-out-of-support.html: link to https://bonitasoft-bonita-documentation-theme-build_preview-pr-230.surge.sh/latest/my-page.html (this is what is configured in model-ui.yml)
- previously, the link sent to https://bonitasoft.github.io/bonita/2021.1/index.html
Locally tested with …
=> feat: provide link to related latest page for "out of support" pages

src/partials/toolbar.hbs
Also remove the link to the downloads page are it doesn't relate to the documentation but to the
products themselves.
Here, we want to warn the reader about an outdated documentation content, not about its usage of
an out-of support product.
previous implementation | 179a073 | e09219b
---- | ---- | ----
Inspired by the Posgres documentation: https://www.postgresql.org/docs/11/app-createdb.html
I'm waiting for the feedback I've requested from people who use out of support content or who are in contact with customers using such content:
- @ugaston
ℹ️ Test page: https://bonitasoft-bonita-documentation-theme-build_preview-pr-234.surge.sh/msg-block-out-of-support.html
=> feat(out-of-support): make the message clearer

src/helpers/isMessageBlockDisplayed.js, src/partials/toc.hbs, src/partials/toolbar.hbs, src/stylesheets/globals/vars.scss, src/stylesheets/toc.scss
Only apply an extra top margin when the HTML generation that a message block is used.
Closes #123
TOC position before and after the fix in the "Showcase" page of the Theme preview:
=> fix: remove extra top margin in the toc when there is no message block

src/js/header-01-theme.js, src/partials/header-content.hbs, src/stylesheets/header.scss
Previously, there were only 2 states for the theme selector: dark or light. If the user didn't touch the theme selector, the system preferences were used without they know it. Once they use the theme selector, it was no longer possible to use the system preferences.
This is now possible to choose to use the theme based on the system preferences. The ball selector has been replaced by an icon rolling, so only the current state of the theme selection is displayed. The icons are taken from Material Symbols.
Closes #231 
**Remaining Tasks**
[PR_242_01_before_change.webm](https://github.com/user-attachments/assets/726a30ea-edd3-4380-add8-756c2b9d43bb)
[PR_242_02_after_change_default_dark.webm](https://github.com/user-attachments/assets/15502821-501e-4481-8851-18b18aefe33f) …
=> feat: choose theme based on system preferences

src/partials/header-content.hbs, src/stylesheets/header.scss
It is now focusable and declare aria attributes to improve accessibility.
[01_before_on_firefox.webm](https://github.com/user-attachments/assets/0f5d56e2-1251-4aa6-9756-4c3fd0b0071f)
[02_PR_243_on_chrome.webm](https://github.com/user-attachments/assets/9c48664f-864f-4c82-9864-f84ae00f4efa)
=> feat: make the theme switcher more accessible

preview-src/tabs.adoc, src/js/header-01-theme.js, src/stylesheets/base.scss, src/stylesheets/doc.scss, src/stylesheets/nav.scss
Apply a transition to the color and background color of elements on all pages.
Limitations: the transition doesn't apply to the following elements:
- DocSearch button keys (gradient)
- home and top right icons in the toolbar/breadcrumb (filter)
Closes #122
> [!NOTE]
> In the following video, transitions are only made from dark to light and vice versa (no use of system preferences). This is for ease of illustration.
The use of system preferences is still available in the final implementation.
[PR_232_20250226-1358_theme_smooth_transition.webm](https://github.com/user-attachments/assets/1281f073-d455-4d12-8a65-8238a5638f11)
=> feat: introduce a smooth transition when switching theme
